# Generated by Django 3.1.7 on 2021-02-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exp_type', models.CharField(max_length=50)),
                ('exp_date', models.DateTimeField(verbose_name='date purchased')),
            ],
        ),
    ]
