# Generated by Django 3.1.7 on 2021-03-24 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exp_type', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonFixedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField()),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.envelopes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('paycheck', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='pay_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.payperiod'),
        ),
        migrations.AddField(
            model_name='envelopes',
            name='pay_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.payperiod'),
        ),
    ]
