# Generated by Django 3.1.7 on 2021-04-06 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20210324_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=9)),
                ('category', models.CharField(max_length=64)),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disbursed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('recipient', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('inflow', models.DecimalField(decimal_places=2, max_digits=8)),
                ('outflow', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fixedexpense',
            name='pay_period',
        ),
        migrations.RemoveField(
            model_name='nonfixedexpense',
            name='envelope',
        ),
        migrations.DeleteModel(
            name='Envelopes',
        ),
        migrations.DeleteModel(
            name='FixedExpense',
        ),
        migrations.DeleteModel(
            name='NonFixedExpense',
        ),
        migrations.DeleteModel(
            name='PayPeriod',
        ),
    ]
